version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 30026:80
  db:
    image: mariadb:latest
    env_file:
      - ".env"
    volumes:
      - kedawan_db:/var/lib/mysql

volumes:
  kedawan_db:
