"""BIG MIGRATE HAHAHA LMAO FUCK ME

Revision ID: 0d5ddfd1f9a5
Revises: 85c24934a478
Create Date: 2023-05-21 01:08:48.946990

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d5ddfd1f9a5'
down_revision = '85c24934a478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fast_links', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.drop_index('slug')

    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.alter_column('country_code',
               existing_type=mysql.CHAR(length=2),
               type_=sa.String(length=2),
               existing_nullable=False)
        batch_op.drop_constraint('FK_visitor_fast_links', type_='foreignkey')
        batch_op.create_foreign_key(None, 'fast_links', ['fast_links_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('FK_visitor_fast_links', 'fast_links', ['fast_links_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.alter_column('country_code',
               existing_type=sa.String(length=2),
               type_=mysql.CHAR(length=2),
               existing_nullable=False)

    with op.batch_alter_table('fast_links', schema=None) as batch_op:
        batch_op.create_index('slug', ['slug'], unique=False)
        batch_op.alter_column('slug',
               existing_type=sa.Text(),
               type_=mysql.TINYTEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
