"""FastLinks: Update table

Revision ID: 3b6525002c6d
Revises: a7e01a05ab0b
Create Date: 2023-05-21 00:14:00.960113

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3b6525002c6d'
down_revision = 'a7e01a05ab0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fast_links', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fast_links', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
