"""Update tables

Revision ID: 661c5a12b49e
Revises: d92f570798f3
Create Date: 2023-05-22 22:06:43.207456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '661c5a12b49e'
down_revision = 'd92f570798f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ip_address_log', schema=None) as batch_op:
        batch_op.alter_column('country_code',
               existing_type=mysql.CHAR(length=2),
               type_=sa.String(length=2),
               existing_nullable=False)

    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.drop_constraint('FK_visitor_fast_links', type_='foreignkey')
        batch_op.drop_constraint('FK_visitor_ip_address_log', type_='foreignkey')
        batch_op.create_foreign_key(None, 'fast_links', ['fast_links_id'], ['id'])
        batch_op.create_foreign_key(None, 'ip_address_log', ['ip_address_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('FK_visitor_ip_address_log', 'ip_address_log', ['ip_address_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key('FK_visitor_fast_links', 'fast_links', ['fast_links_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('ip_address_log', schema=None) as batch_op:
        batch_op.alter_column('country_code',
               existing_type=sa.String(length=2),
               type_=mysql.CHAR(length=2),
               existing_nullable=False)

    # ### end Alembic commands ###
