"""FastLinks: Set slug to be unique

Revision ID: 83d59959bec9
Revises: 661c5a12b49e
Create Date: 2023-05-26 17:37:32.548485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83d59959bec9'
down_revision = '661c5a12b49e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fast_links', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fast_links', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
