"""FastLinks: Update table

Revision ID: a7e01a05ab0b
Revises: 707f8ad55492
Create Date: 2023-05-21 00:12:23.753252

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a7e01a05ab0b'
down_revision = '707f8ad55492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fast_links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visitor', sa.Integer(), nullable=True))
        batch_op.alter_column('slug',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fast_links', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.Text(length=10),
               type_=mysql.TINYTEXT(),
               existing_nullable=False)
        batch_op.drop_column('visitor')

    # ### end Alembic commands ###
