"""FastLinks: Set default visitor to 0

Revision ID: f2ef997605e5
Revises: 0d5ddfd1f9a5
Create Date: 2023-05-21 01:17:32.274236

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f2ef997605e5'
down_revision = '0d5ddfd1f9a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fast_links', schema=None) as batch_op:
        batch_op.alter_column('visitor',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fast_links', schema=None) as batch_op:
        batch_op.alter_column('visitor',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###
